CREATE TABLE IF NOT EXISTS `KH_TB_GUILDS` (
	`id` INTEGER PRIMARY KEY  AUTOINCREMENT,
	`guild_id` TEXT UNIQUE NOT NULL,
  	`name` TEXT NOT NULL,
    `prefix` TEXT DEFAULT "!" NOT NULL,
	`invited_at` datetime DEFAULT (datetime('now','localtime'))
);

-- INSERT INTO KH_TB_GUILDS (guild_id,name,prefix) VALUES ('697180940127961128','Darth Code','!'), ('911248622421704704','<Undefined />','.');

CREATE TABLE IF NOT EXISTS `KH_TB_TRELLO` (
	`ID` INTEGER PRIMARY KEY  AUTOINCREMENT,
	`GUILD_ID` TEXT UNIQUE NOT NULL,
  	`TOKEN` TEXT NOT NULL,
    `DEFAULT_BOARD` TEXT DEFAULT NULL,
	`LINKED_AT` datetime DEFAULT (datetime('now','localtime')),
	`LINKED_BY` TEXT NOT NULL,
	FOREIGN KEY (`GUILD_ID`) REFERENCES `KH_TB_GUILDS`(`guild_id`)
);

CREATE TABLE IF NOT EXISTS `KH_TB_AZURE` (
	`ID` INTEGER PRIMARY KEY  AUTOINCREMENT,
	`GUILD_ID` TEXT UNIQUE NOT NULL,
  	`TOKEN` TEXT NOT NULL,
    `DEFAULT_PROJECT` TEXT DEFAULT NULL,
	`LINKED_AT` datetime DEFAULT (datetime('now','localtime')),
	`LINKED_BY` TEXT NOT NULL,
	FOREIGN KEY (`GUILD_ID`) REFERENCES `KH_TB_GUILDS`(`guild_id`)
);

CREATE TABLE IF NOT EXISTS `KH_TB_USERS` (
	`ID` INTEGER PRIMARY KEY  AUTOINCREMENT,
	`GUILD_ID` TEXT NOT NULL,
  	`USER_ID` TEXT NOT NULL,
    `NAME` TEXT DEFAULT NULL,
    `DISCRIMINATOR` TEXT DEFAULT NULL,
	`JOINED_AT` datetime DEFAULT (datetime('now','localtime')),
	`XP` INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `KH_TB_PROCESSOS` (
	`ID` TEXT PRIMARY KEY,
	`GUILD` TEXT NOT NULL,
	`USER` TEXT,
	`MSG` TEXT,
	`KEY` TEXT NOT NULL,
	`STAGE` NUMBER NOT NULL,
	`EXPIRES` datetime DEFAULT (datetime('now','+30 minutes','localtime'))
	
);

CREATE TABLE IF NOT EXISTS `KH_TB_REACTIONS` (
	`ID` INTEGER PRIMARY KEY AUTOINCREMENT,
	`GUILD` TEXT NOT NULL,
	`PROCESSO` TEXT NOT NULL,
	`EMOJI` TEXT NOT NULL,
	`VALUE` TEXT NOT NULL,
	FOREIGN KEY (`PROCESSO`) REFERENCES `KH_TB_PROCESSOS`(`ID`)
);
-- ALTER TABLE `KH_TB_AZURE` ADD COLUMN  `ORGANIZATION` VARCHAR(255) DEFAULT NULL;