CREATE TABLE IF NOT EXISTS `KH_TB_GUILDS` (
	`id` INTEGER PRIMARY KEY  AUTOINCREMENT,
	`guild_id` TEXT UNIQUE NOT NULL,
  	`name` TEXT NOT NULL,
    `prefix` TEXT DEFAULT "!" NOT NULL,
	`invited_at` datetime DEFAULT CURRENT_TIMESTAMP
);

-- INSERT INTO KH_TB_GUILDS (guild_id,name,prefix) VALUES ('697180940127961128','Darth Code','!'), ('911248622421704704','<Undefined />','.');

CREATE TABLE IF NOT EXISTS `KH_TB_TRELLO` (
	`ID` INTEGER PRIMARY KEY  AUTOINCREMENT,
	`GUILD_ID` TEXT UNIQUE NOT NULL,
  	`TOKEN` TEXT NOT NULL,
    `DEFAULT_BOARD` TEXT NOT NULL,
	`LINKED_AT` datetime DEFAULT CURRENT_TIMESTAMP,
	`LINKED_BY` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `KH_TB_AZURE` (
	`ID` INTEGER PRIMARY KEY  AUTOINCREMENT,
	`GUILD_ID` TEXT UNIQUE NOT NULL,
  	`TOKEN` TEXT NOT NULL,
    `DEFAULT_PROJECT` TEXT NOT NULL,
	`LINKED_AT` datetime DEFAULT CURRENT_TIMESTAMP,
	`LINKED_BY` TEXT NOT NULL
);
